-- MySQL Script generated by MySQL Workbench
-- Fri May 22 17:09:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema idea-dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema idea-dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `idea-dev` DEFAULT CHARACTER SET utf8 ;
USE `idea-dev` ;

-- -----------------------------------------------------
-- Table `idea-dev`.`AD_privilegio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idea-dev`.`AD_privilegio` ;

CREATE TABLE IF NOT EXISTS `idea-dev`.`AD_privilegio` (
  `AD_id` INT NOT NULL AUTO_INCREMENT,
  `AD_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AD_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idea-dev`.`AA_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idea-dev`.`AA_pessoa` ;

CREATE TABLE IF NOT EXISTS `idea-dev`.`AA_pessoa` (
  `AA_id` INT NOT NULL AUTO_INCREMENT,
  `AA_email` VARCHAR(255) NOT NULL,
  `AA_nomecompleto` VARCHAR(255) NULL DEFAULT NULL,
  `AA_nome` VARCHAR(100) NULL DEFAULT NULL,
  `AA_sobrenome` VARCHAR(155) NULL DEFAULT NULL,
  `AA_created` DATETIME NOT NULL,
  `AA_updated` DATETIME NOT NULL,
  `AD_id` INT NOT NULL,
  PRIMARY KEY (`AA_id`),
  INDEX `fk_AA_pessoa_AD_privilegio1_idx` (`AD_id` ASC) ,
  CONSTRAINT `fk_AA_pessoa_AD_privilegio1`
    FOREIGN KEY (`AD_id`)
    REFERENCES `idea-dev`.`AD_privilegio` (`AD_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idea-dev`.`AC_terceiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idea-dev`.`AC_terceiro` ;

CREATE TABLE IF NOT EXISTS `idea-dev`.`AC_terceiro` (
  `AC_id` INT NOT NULL AUTO_INCREMENT,
  `AC_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AC_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idea-dev`.`AB_pessoaTerceiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idea-dev`.`AB_pessoaTerceiro` ;

CREATE TABLE IF NOT EXISTS `idea-dev`.`AB_pessoaTerceiro` (
  `AA_pessoa_id` INT NOT NULL,
  `AC_terceiro_AC_id` INT NOT NULL,
  `AB_pessoa_terceiro_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AA_pessoa_id`, `AC_terceiro_AC_id`),
  INDEX `fk_AB_pessoaTerceiro_AC_terceiro1_idx` (`AC_terceiro_AC_id` ASC) ,
  CONSTRAINT `fk_AA_pessoaTerceiro_AA_pessoa`
    FOREIGN KEY (`AA_pessoa_id`)
    REFERENCES `idea-dev`.`AA_pessoa` (`AA_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AB_pessoaTerceiro_AC_terceiro1`
    FOREIGN KEY (`AC_terceiro_AC_id`)
    REFERENCES `idea-dev`.`AC_terceiro` (`AC_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
