-- MySQL Script generated by MySQL Workbench
-- Fri Apr 24 15:09:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`AA_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AA_pessoa` (
  `AA_userId` INT NOT NULL AUTO_INCREMENT,
  `AA_googleId` INT NOT NULL,
  `AA_email` VARCHAR(255) NOT NULL,
  `AA_fullName` VARCHAR(255) NOT NULL,
  `AA_firstName` VARCHAR(100) NOT NULL,
  `AA_lastName` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`AA_userId`),
  UNIQUE INDEX `AA_email_UNIQUE` (`AA_email` ASC),
  UNIQUE INDEX `AA_googleId_UNIQUE` (`AA_googleId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AB_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AB_admin` (
  `AB_id` INT NOT NULL AUTO_INCREMENT,
  `AA_id` INT NOT NULL,
  PRIMARY KEY (`AB_id`, `AA_id`),
  INDEX `fk_AB_admin_AA_pessoa_idx` (`AA_id` ASC),
  CONSTRAINT `fk_AB_admin_AA_pessoa`
    FOREIGN KEY (`AA_id`)
    REFERENCES `mydb`.`AA_pessoa` (`AA_userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AC_palestrante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AC_palestrante` (
  `AC_id` INT NOT NULL AUTO_INCREMENT,
  `AA_id` INT NOT NULL,
  PRIMARY KEY (`AC_id`, `AA_id`),
  INDEX `fk_AC_palestrante_AA_pessoa1_idx` (`AA_id` ASC),
  CONSTRAINT `fk_AC_palestrante_AA_pessoa1`
    FOREIGN KEY (`AA_id`)
    REFERENCES `mydb`.`AA_pessoa` (`AA_userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AD_participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AD_participante` (
  `AD_id` INT NOT NULL AUTO_INCREMENT,
  `AA_id` INT NOT NULL,
  PRIMARY KEY (`AD_id`, `AA_id`),
  INDEX `fk_AD_participante_AA_pessoa1_idx` (`AA_id` ASC),
  CONSTRAINT `fk_AD_participante_AA_pessoa1`
    FOREIGN KEY (`AA_id`)
    REFERENCES `mydb`.`AA_pessoa` (`AA_userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
